services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:4-24-trixie
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - app-network
    depends_on:
      - valkey

  valkey:
    image: valkey/valkey:9.0-alpine
    networks:
      - app-network
    volumes:
      - valkey-data:/data
    healthcheck:
      test: [ 'CMD', 'valkey-cli', 'ping' ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  valkey-data:


networks:
  app-network:
    driver: bridge
